### ISSUE TITLE
[Idea] Saving your creatures

### ISSUE THREAD

**Issue by ikbendewilliam** [carykh/evolutionSteer#8]
I currently don't have the time to create it myself, but in your video, you said something about that you want to be able to save your progress. You can do this with a lot of things, I suggest using saveTable (https://processing.org/reference/saveTable_.html) and just have every creature return a tableRow with all muscles, nodes and brain in it. This would be useful if anyone has a bug, they can simply share their creatures with you and you can also share the creatures you made in the video with your viewers.

**Comment by L-four** [comment]
darkracer has already implemented saving as json as per this PR https://github.com/carykh/evolutionSteer/pull/7
